#! /bin/bash - 

# Script for finding frequecies of characters in files with 
# a given extension

# Usage: kb_stat [path] [-e extension]

# if path is not specified scripts drills down current directory
# if extension is not specified script uses '*.py'

extension_switch="-e"
extension=".py"
path="."

if [ "$#" -ge 4 ]; then
    echo Expecting at most 3 arguments by $# is given
    exit 1
fi

while [ $# -gt 0 ]
do
    if [ "$1" = "$extension_switch" ]; then
        extension="$2"
        shift
    else
        path="$1"
    fi
    shift
done 

tmp=$(mktemp)

files=$(find "$path" -name "*$extension" -type f | xargs)

for f in $files
do
    tr '[:upper:]' '[:lower:]' < $f | tr -d '[:space:]' >> "$tmp"
done

sed 's/\(.\)/\1\n/g' "$tmp" | sort | uniq -c | sort -k2

rm "$tmp"